import tiposDeSimbolos from '../tipos-de-simbolos/lexico-regular';

export const palavrasReservadas = {
    ate: tiposDeSimbolos.ATE,
    cadeia: tiposDeSimbolos.CADEIA,
    caractere: tiposDeSimbolos.CARACTERE,
    de: tiposDeSimbolos.DE,
    e: tiposDeSimbolos.E,
    enquanto: tiposDeSimbolos.ENQUANTO,
    entao: tiposDeSimbolos.ENTAO,
    escrever: tiposDeSimbolos.ESCREVER,
    faca: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    fim: tiposDeSimbolos.FIM,
    inicio: tiposDeSimbolos.INICIO,
    inteiro: tiposDeSimbolos.INTEIRO,
    ler: tiposDeSimbolos.LER,
    logico: tiposDeSimbolos.LOGICO,
    modulo: tiposDeSimbolos.MODULO,
    nao: tiposDeSimbolos.NEGACAO,
    ou: tiposDeSimbolos.OU,
    para: tiposDeSimbolos.PARA,
    passo: tiposDeSimbolos.PASSO,
    real: tiposDeSimbolos.REAL,
    repita: tiposDeSimbolos.REPITA,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    variaveis: tiposDeSimbolos.VARIAVEIS,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
    vetor: tiposDeSimbolos.VETOR,
};
